/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a fully installed project.
// It is committed here so the scaffold type-checks cleanly once dependencies are installed.
