// Verbatim port of the Scrolls app legal documents (iOS `LegalViews.swift` /
// Android `LegalContent.kt`). Platform-specific lines (app-store subscriptions,
// push services) are neutralized to cover both iOS and Android, since the web
// serves users on both platforms.

export const SCROLLS_SUPPORT_EMAIL = "support@scrolls.app";

export type LegalSection = { title: string; body: string };

export const privacySections: LegalSection[] = [
  {
    title: "1. Overview",
    body: "Scrolls is a social platform for creating, sharing, and discovering posts, articles, photos, photo carousels, videos, podcasts, music releases, live streams, moments, comments, replies, rescrolls, mentions, collaborator tags, pinned posts, circles messages, voice messages, and sponsored placements. This Privacy Policy explains what information we collect, how we use it, when we share it, and the choices available to you. It applies alongside our Terms of Service and our Community Guidelines, which you also agree to when you use Scrolls."
  },
  {
    title: "2. Information You Provide",
    body: "When you create or update an account, you may provide information such as a username, display name, bio, avatar image, optional profile video avatar, signature image, website URL, home city, additional followed cities, business details, and optional support or payment links where available. You also provide content and related metadata when you publish posts, articles, photo carousels, videos, captions, location tags, comments, replies, rescrolls, mentions, collaborator tags, pinned-post selections, circles messages, voice messages, podcasts, music releases (including release dates, record labels, lyrics, liner notes, explicit flags, and linked music videos), live stream titles, tip messages, and advertising or promotional materials made available to your account."
  },
  {
    title: "3. Information Generated by Use",
    body: "As you use Scrolls, we generate service data such as follows, comments, replies, rescroll activity, search activity (including lyric search), mention and collaborator relationships, circles activity, voice-message delivery state, live-stream session state and viewer counts, notification state, hidden-post selections, blocked-account lists, report events and their review outcomes, ad interaction events, and the playback or delivery diagnostics needed to run product features. We also process subscription status, moderation outcomes (including automated and reviewer actions), abuse-prevention signals, managed-account relationships, authentication and password-reset events, and technical information such as crash and performance data."
  },
  {
    title: "4. Media and Device Storage",
    body: "Photos, videos, audio, cover art, voice recordings, and similar media you choose to use in Scrolls may be processed on your device and uploaded to our storage or streaming providers so they can be delivered in feeds, profiles, live sessions, circles, and other app surfaces. Published media may be accessible by URL anywhere your content is visible. To operate playback and previews, we may also generate live stream derivatives, thumbnails, previews, or archived versions. Temporary local files created during processing are intended to be removed after use."
  },
  {
    title: "5. Permissions",
    body: "Depending on the features you use, Scrolls may request access to Photos and media (read and add), Camera, Microphone, Contacts, Location (While In Use), and Notifications. These permissions support features such as posting media, recording voice messages and live audio, creating live streams, tagging posts with a city, inviting friends from your address book, and receiving alerts. Before we show the system permission prompt for notifications, we explain in-app what notifications you'll receive so you can make an informed choice. You can change these permissions at any time in your device's Settings, but some features may not work without the required access."
  },
  {
    title: "6. Contacts (On-Device Only)",
    body: "If you grant Contacts access for the invite-friends feature, your contacts are read on your device to populate the local invite picker. Contact names, phone numbers, and email addresses are not uploaded to our servers, are not used for advertising, and are not used to match you against other Scrolls users on the server side. Closing or revoking access stops further reads immediately."
  },
  {
    title: "7. Location",
    body: "If you grant Location While In Use access, Scrolls uses your device's location only to derive a city name for tagging posts and for showing city-based feeds. We do not collect precise coordinates beyond what is needed to resolve the city, and we do not run background location tracking. You can revoke Location access at any time in your device's Settings, and posts you have already published keep the city you originally tagged unless you edit them."
  },
  {
    title: "8. Advertising and Sponsored Content",
    body: "Scrolls may display sponsored or curated promotional content in parts of the service, including feed and splash-style placements. Sponsored content can include media, captions, and destination links. Eligible users may also be allowed to submit advertising or promotional materials for review before publication. Subscription status may affect whether certain ad surfaces are shown. We may process impression, delivery, review, moderation, and link-opening data needed to operate and improve these placements. Scrolls does not track you across other companies' apps and websites."
  },
  {
    title: "9. How We Use Data",
    body: "We use your information to authenticate accounts, support account recovery, operate feeds, search, profiles, discovery features, circles messaging, voice messages, notifications, live streaming, and moments playback, and to publish and display content throughout the service. We also use data to prevent abuse, enforce our Community Guidelines and Terms, review user reports and ad submissions, surface moderation decisions to authorized reviewers, respond to support requests, and improve reliability, safety, and performance. Scrolls does not sell personal information for money."
  },
  {
    title: "10. Sharing and Visibility",
    body: "Posts and profile content may be visible to other users throughout the product, including in feeds, profiles, search, discovery surfaces, live experiences, and moments, depending on how the feature is designed to work. Interactions such as comments, replies, follows, mentions, collaborator tags, and rescrolls may also be visible in context. Pinned posts are highlighted on your profile. Circles messages, voice messages, and tip messages are visible to the participants of the relevant conversation, post, or live session. External links, payment links, and website links you add to your profile or content may be visible wherever they appear and may lead to destinations controlled by third parties."
  },
  {
    title: "11. Safety Tools (Blocking, Hiding, Reporting)",
    body: "You can block another account at any time. Once blocked, the account cannot see your posts, message you, appear in your feeds, or interact with your content; you can manage and undo blocks from Profile → Blocked accounts. You can also hide an individual post from your own feed without affecting the author. You can report posts, profiles, live streams, comments, music tracks, voice messages, circle messages, and avatars; reports are reviewed by Scrolls under our Community Guidelines, typically within 24 hours. To support review, reports are visible to authorized Scrolls reviewers along with the reported content, the reporter's account, and the reason and any note you add."
  },
  {
    title: "12. Live Stream Moderation",
    body: "Live broadcasts are subject to the same rules as posts. Reports submitted against an active broadcast may be reviewed automatically as well as by humans; if a stream receives a high number of distinct reports in a short window, it may be ended automatically as a safety measure and the contributing reports may be auto-resolved. Audit information about that decision is retained for moderation review."
  },
  {
    title: "13. Moderation and Safety",
    body: "Scrolls uses automated systems and human review to help detect prohibited conduct and content, including spam, abuse, fraud, hate speech, harassment, and explicit-content violations. We may remove content, reduce distribution, deny advertising submissions, limit features, end broadcasts, restrict accounts, or suspend or terminate access when our policies are violated. We may also restrict certain deceptive synthetic or AI-generated media uses. Authorized founder and admin reviewers can see queued reports and resolution status, including the reporter and the reason provided."
  },
  {
    title: "14. Account Deletion",
    body: "You can delete your account from inside the app or from your account settings on the web at any time. Deleting your account removes your account record and starts the removal of your posts, profile media, and related content from active service surfaces. Deletion is durable: your posts will not return after re-install. Some records may be retained for a limited period when reasonably necessary for security, abuse prevention, support, legal compliance, or dispute resolution. Deletion does not unblock or unfollow accounts on third-party platforms you may have linked to from your profile."
  },
  {
    title: "15. Data Retention",
    body: "Retention periods vary based on the type of data and the feature involved. Some data, such as notifications, circles message history, voice messages, live or moment-related media, and other time-limited features, may expire automatically under product rules or plan limits. Reports and their resolution status are retained for safety and audit purposes. We may keep certain records longer when reasonably necessary for security, abuse prevention, support, legal compliance, or dispute resolution."
  },
  {
    title: "16. Subscriptions and Payments",
    body: "Paid features are offered through the App Store (iOS) and Google Play (Android) subscriptions. The applicable app store handles billing, renewal, cancellation, and refunds under its terms. Scrolls stores the entitlement information needed to enable paid features, such as plan status and related feature access. Where creators have chosen to display external support or payment links (such as Venmo or Cash App) on their profile, those links lead to third-party services with their own terms and privacy policies; any off-platform payment is handled by the third-party destination, not by Scrolls, and Scrolls does not receive transaction details from those services. In-app tip messages are stored and delivered through Scrolls; the financial transaction itself is not."
  },
  {
    title: "17. Push Notifications",
    body: "If you allow notifications, we may send alerts about mentions, comments and replies, new followers, collaborator tags, live streams from people you follow, and similar product events. We use platform push services (Apple Push Notification service on iOS and Firebase Cloud Messaging on Android) for delivery and store the device push token associated with your account so we can route notifications to your device; you can disable notifications at any time in your device's Settings."
  },
  {
    title: "18. Your Rights and Choices",
    body: "You can update many of your account details in the app or on the web, including profile fields, avatar media, signature image, home city, additional followed cities, pinned post, follows, blocks, hidden posts, and certain content choices. You can also reset your password and control app permissions through your device's Settings. Subscription management takes place through your app store's subscription settings. You can delete your account from inside the app or from your account settings. Depending on where you live, you may also have legal rights to request access to, correction of, deletion of, or limits on the processing of your information."
  },
  {
    title: "19. Contact",
    body: `For privacy requests or legal questions about this policy, contact ${SCROLLS_SUPPORT_EMAIL}. We may request account verification before processing account-specific requests.`
  }
];

export const termsSections: LegalSection[] = [
  {
    title: "1. Acceptance",
    body: "By creating an account, completing sign-up, or using Scrolls, you agree to these Terms of Service, our Privacy Policy, and our Community Guidelines. The Community Guidelines describe the conduct and content rules you accept by using Scrolls and are incorporated into these Terms. If you do not agree, you may not use the service. If we update these Terms and you continue to use Scrolls after the effective date, that continued use means you accept the updated Terms unless the law requires something more."
  },
  {
    title: "2. Eligibility and Accounts",
    body: "You must be legally allowed to use Scrolls where you live. You agree to provide accurate account information, keep your login credentials secure, and remain responsible for activity that occurs through your account. You may not impersonate others, create deceptive or confusing accounts, evade product limits or policies, or use unauthorized automation to create or control accounts. If Scrolls supports managed or linked account features, you may only use them for accounts you are authorized to control."
  },
  {
    title: "3. User Content",
    body: "You keep ownership of the content you submit to Scrolls. By posting or uploading content, you give Scrolls a worldwide, non-exclusive, royalty-free license to host, process, store, display, stream, reproduce, and distribute that content as needed to operate and improve the service. You represent that you have the rights necessary to post the content, including any rights related to music, audio, lyrics, liner notes, credits, cover art, images, photo carousels, videos, music videos, live-streamed material, and likenesses where applicable. When you tag another account as a collaborator on a post, you confirm that the tag is accurate and not used to harass or impersonate."
  },
  {
    title: "4. Product Limits and Availability",
    body: "Scrolls may apply feature or usage limits by plan, account type, or product surface. These may include posting limits, media limits, live-streaming limits, photo-carousel limits, circles retention windows, voice-message retention, ad eligibility rules, or account-switching limits. Certain features may also change or become unavailable based on account status, region, policy, or technical constraints."
  },
  {
    title: "5. Ads and Promotional Content",
    body: "Scrolls may place sponsored posts, splash ads, or other promotional placements throughout the service. The way these placements appear may differ by account tier or subscription status. Placement rules, labels, ordering, and availability may change over time. Advertising or promotional materials submitted by users may be rejected, delayed, limited, or removed at Scrolls' discretion."
  },
  {
    title: "6. External Links and Payment Links",
    body: "Scrolls may allow website links, support links, and external payment links (such as Venmo or Cash App) where eligible. Those links lead to third-party services with their own terms; Scrolls is not the seller of record for any external transaction, does not facilitate payment, does not receive transaction details, and does not handle refunds for off-platform transfers. You are responsible for the destinations you share and for any content available at those destinations."
  },
  {
    title: "7. Acceptable Use and Community Guidelines",
    body: "Your use of Scrolls is governed by our Community Guidelines in addition to these Terms. You may not use Scrolls for unlawful, abusive, deceptive, or infringing purposes. Prohibited conduct includes explicit nudity or sexual exploitation, content involving minors in any sexual or exploitative context, harassment, threats, hate speech, doxxing, spam, scams, malware, fraud, unauthorized scraping, policy evasion, and infringing use of music or other copyrighted media. Scrolls may also block certain external links or services and may restrict deceptive synthetic or AI-generated content practices."
  },
  {
    title: "8. Mentions, Comments, Collaborator Tags, and Messaging",
    body: "You are responsible for how you use mentions, comments, replies, collaborator tags, live comments, circles messaging, and voice messages. These features may not be used for abuse, intimidation, stalking, coordinated harassment, or repeated unwanted contact. Scrolls may remove related content, reduce visibility, or restrict access to these features when our rules are violated."
  },
  {
    title: "9. Live Streaming, Audio, and Media Rights",
    body: "If you use live streaming, podcast, or music features, you are responsible for making sure the material you broadcast or upload is lawful and properly licensed. That includes music, lyrics, liner notes, backing tracks, samples, cover art, video, music videos, and any third-party likenesses. Scrolls may interrupt, mute, end, block, remove, or decline to archive media that violates policy, appears technically broken, or creates legal or safety concerns. Live broadcasts that receive a sustained pattern of distinct user reports in a short window may be ended automatically as a safety measure."
  },
  {
    title: "10. Safety Tools (Blocking, Hiding, Reporting)",
    body: "Scrolls provides tools you can use to manage your experience and report content that violates our policies. You can block another account from your feeds and conversations and manage that list from Profile → Blocked accounts; you can hide individual posts from your feed; and you can report posts, profiles, live streams, comments, music tracks, voice messages, circle messages, and avatars using the flag icon on each surface. We aim to review reports within 24 hours and may confirm or dismiss them at our discretion. Submitting false or abusive reports may itself violate these Terms."
  },
  {
    title: "11. Enforcement",
    body: "Scrolls may investigate suspected violations and enforce these Terms and our Community Guidelines through warnings, content removal, reduced distribution, feature restrictions, automated or human-triggered live-stream termination, account-scope restrictions, temporary suspensions, or permanent account termination. Enforcement may also include advertising review decisions, report outcomes, evidence preservation, and cooperation with valid legal process where required."
  },
  {
    title: "12. Account Deletion",
    body: "You can delete your account from inside the app at any time from Profile → Delete account, or from your account settings on the web. Deleting your account starts the removal of your posts, profile media, and related content from active service surfaces. Deletion is durable: your posts will not return after re-install. Some records may be retained for a limited period when reasonably necessary for security, abuse prevention, support, legal compliance, or dispute resolution. If you used external payment links on your profile, deletion does not affect transactions or relationships with those third-party services."
  },
  {
    title: "13. Subscriptions",
    body: "Paid features are offered through the App Store and Google Play auto-renewable subscriptions. Billing, cancellation, renewal, and refunds are handled by the applicable app store under its terms. Access to paid features depends on active entitlement status. Scrolls may change paid feature bundles, limits, or eligibility over time."
  },
  {
    title: "14. Third-Party Services",
    body: "Scrolls relies on third-party services and infrastructure, including Apple and Google platform services, cloud and media infrastructure, streaming providers, push notification providers, email delivery providers, and external share destinations. Those services operate under their own terms and policies. Scrolls is not responsible for third-party outages, external platform account actions, or the handling of content after it leaves Scrolls."
  },
  {
    title: "15. Disclaimers and Liability",
    body: 'Scrolls is provided "as is" and "as available" to the fullest extent allowed by law, without warranties of any kind, including implied warranties of merchantability, fitness for a particular purpose, or non-infringement. To the maximum extent permitted by law, Scrolls and its operators are not liable for indirect, incidental, consequential, special, or punitive damages, or for lost profits, lost data, business interruption, advertising performance issues, or media or livestream interruptions.'
  },
  {
    title: "16. Changes",
    body: "Scrolls may update these Terms, our Privacy Policy, and our Community Guidelines from time to time for legal, security, business, or product reasons. Updated versions may be presented in the app and become effective on the listed date. Significant updates to the Community Guidelines may require you to acknowledge them again before continuing to use Scrolls. If you continue to use Scrolls after the effective date, you agree to the updated documents unless the law requires separate consent."
  },
  {
    title: "17. Contact",
    body: `For legal notices, policy disputes, or Terms questions, contact ${SCROLLS_SUPPORT_EMAIL}.`
  }
];
