import type { Metadata } from "next";
import { AppCTA } from "@/components/AppCTA";
import { AppSmartBanner } from "@/components/AppSmartBanner";
import { PostCard } from "@/components/post/PostCard";
import { SiteHeader } from "@/components/SiteHeader";
import { fetchPost } from "@/lib/api/scrolls";
import { parseArticle } from "@/lib/article/article";
import { parseMusicPost, photoCarouselURLs, releaseTypeLabel, strippedCaption } from "@/lib/music/markers";
import type { ScrollsPost } from "@/lib/types/scrolls";

const BASE = process.env.NEXT_PUBLIC_SCROLLS_WEB_BASE_URL ?? "https://scrolls.adastra.love";

type Params = { params: Promise<{ postId: string }> };

function truncate(text: string, max = 200): string {
  const clean = text.replace(/\s+/g, " ").trim();
  return clean.length > max ? `${clean.slice(0, max - 1)}…` : clean;
}

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const { postId } = await params;
  const url = `${BASE}/scroll/${postId}`;
  // og:image / twitter:image are generated by the sibling opengraph-image and
  // twitter-image routes, so they're intentionally not set here.
  try {
    const post = await fetchPost(postId);
    if (!post) throw new Error("unavailable");

    // Rescrolls credit the original author; canonical points at the original.
    const rescroll = post.rescrollOrigin ?? post.rescroll_origin ?? null;
    const author = rescroll?.user ?? post.author ?? post.user;
    const displayName = author?.displayName ?? author?.display_name ?? author?.username ?? "Scrolls";
    const handle = author?.username ? `@${author.username}` : "Scrolls";

    const music = parseMusicPost(post.caption);
    const article = parseArticle(post);

    let title = `${displayName} on Scrolls`;
    let description = `View this scroll from ${handle}.`;
    let ogType: "website" | "article" = "website";

    if (music.isMusic || music.isPodcast) {
      title = music.title ? `${music.title} by ${displayName}` : `${displayName} on Scrolls`;
      const meta = [releaseTypeLabel(music.releaseType), music.genre, music.recordLabel].filter(Boolean).join(" · ");
      const tracks = music.tracks.map((track) => track.title).filter(Boolean).join(", ");
      description = truncate([tracks || (music.isPodcast ? "Podcast" : "Music"), meta].filter(Boolean).join(" — "));
    } else if (article) {
      title = article.headline;
      description = truncate(article.blocks.map((block) => block.text).join(" "));
      ogType = "article";
    } else {
      const clean = strippedCaption(post.caption ?? undefined)?.trim();
      const carousel = photoCarouselURLs(post.caption);
      const parts: string[] = [];
      if (rescroll && post.author?.username) parts.push(`@${post.author.username} rescrolled @${author?.username ?? ""}`);
      if (clean) parts.push(clean);
      if (carousel.length) parts.push(`${carousel.length + 1} photos`);
      description = truncate(parts.join(" · ") || `View this scroll from ${handle}.`);
    }

    return {
      title,
      description,
      alternates: { canonical: rescroll?.postID ? `${BASE}/scroll/${rescroll.postID}` : url },
      openGraph: { title, description, url, siteName: "Scrolls", type: ogType },
      twitter: { card: "summary_large_image", title, description }
    };
  } catch {
    // Private, deleted, or temporarily unavailable.
  }
  return {
    title: "Scroll",
    description: "Open this Scrolls post.",
    alternates: { canonical: url },
    openGraph: { title: "Open this scroll", description: "View this post in Scrolls.", url, siteName: "Scrolls" },
    twitter: { card: "summary_large_image", title: "Open this scroll", description: "View this post in Scrolls." }
  };
}

export default async function ScrollPage({ params }: Params) {
  const { postId } = await params;
  let post: ScrollsPost | null = null;
  try {
    post = await fetchPost(postId);
  } catch {
    post = null;
  }

  return (
    <div>
      <SiteHeader />
      <AppSmartBanner deepLink={`scrolls://scroll/${postId}`} label="Open this scroll in the app" />
      <section className="mx-auto grid min-h-[70svh] max-w-2xl gap-6 px-5 py-10">
        {post ? (
          <>
            <div className="text-center">
              <p className="text-sm uppercase tracking-[0.22em] text-scrolls-gold">Shared scroll</p>
              <h1 className="mt-3 text-4xl font-black">View this post on Scrolls</h1>
            </div>
            <PostCard post={post} />
            <div className="flex flex-wrap justify-center gap-3">
              <a href={`scrolls://scroll/${postId}`} className="rounded-full bg-scrolls-blue px-5 py-3 text-sm font-bold">
                Open in app
              </a>
              <AppCTA />
            </div>
          </>
        ) : (
          <div className="self-center rounded-[2rem] border border-white/10 bg-scrolls-panel p-8 text-center">
            <p className="text-sm uppercase tracking-[0.22em] text-scrolls-gold">Shared scroll</p>
            <h1 className="mt-3 text-4xl font-black">Open this post in Scrolls</h1>
            <p className="mt-4 text-sm text-white/55">
              This post is private, deleted, or temporarily unavailable on the web.
            </p>
            <p className="mt-3 break-all text-xs text-white/35">{postId}</p>
            <div className="mt-8 flex flex-wrap justify-center gap-3">
              <a href={`scrolls://scroll/${postId}`} className="rounded-full bg-scrolls-blue px-5 py-3 text-sm font-bold">
                Open in app
              </a>
              <AppCTA />
            </div>
          </div>
        )}
      </section>
    </div>
  );
}
